### ISSUE TITLE
发现一个好东西

### ISSUE THREAD

**Issue by akakoori** [LER0ever/Israfil#4]
https://github.com/AnyListen/AnyListen

估计这个东西对你应该有帮助。

**Comment by LER0ever** [comment]
这个项目我注意到了，作者是原"音乐间谍"的开发者。但是，他是用.net core写的，我是纯C++；再加上我API部分已经写完了，正在撸UI。所以，现在Qt/QML界面的demo或许会对我更有帮助。
还是谢谢你的分享。
